// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbjmoxzhjmxcttwupjmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtiam1veHpoam14Y3R0d3Vwam1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDk5NzcsImV4cCI6MjA2NjQ4NTk3N30.JCP6bklOrRgizyScYUyKDsGgV2c82uNo0vIB2EOZtow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});